hl.on("hyprland.start", function()
  hl.exec_cmd('echo "Xft.dpi: 96" | xrdb -merge')
  hl.exec_cmd("xprop -root -f _XWAYLAND_GLOBAL_OUTPUT_SCALE 32c -set _XWAYLAND_GLOBAL_OUTPUT_SCALE 1")
  hl.exec_cmd("swaync -c /home/surya/.config/swaync/config.json -s /home/surya/.config/swaync/style.css")
  -- hyprlauncher daemon (no window); Super+Space opens it via binds
  hl.exec_cmd("hyprlauncher -d")
  -- hyprpolkitagent is started by services.hyprpolkitagent (systemd user unit)
  hl.exec_cmd("ags run .config/ags/yami.js")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("hyprpaper")
end)
